### ISSUE TITLE
Try to add a new way to extract the values of the arguments

### ISSUE THREAD

**Issue by forax** [sormuras/command-line-interface#10]
see
https://github.com/sormuras/command-line-interface/blob/main/test/test/EnumTests.java

This is currently a test (in a TDD way) to explore how to get the argument values without using a record.

There are several ways, obviously at some point we will have to make a choice.

The idea is to provide a Map(K, Option) and let the user to extract the argument value from K after the Splitter has returns the arguments.
The configuration is a glorified Map builder.

**Comment by sormuras** [comment]
> The configuration is a **_glorified_** Map builder.

🤓 

We did something similar with turning the `List<Value>` into a `Map<String, Value>`, where each option name (they are unique)  is a key.

**Comment by forax** [comment]
Technically you can give an access by an index or by a name and only allocate the Map if the name is used.
see https://github.com/sormuras/command-line-interface/commit/3c8faccecfdc72da9127086ee2c6c5ece7da3e25#diff-8a67fad31a23663cae006121d6b49bfd3f448bb12e8b513a78ad2714aa60a7acR359

**Comment by forax** [comment]
I also prefer to not expose the Map directly because you can provide a more typesafe way to access to the data
see https://github.com/sormuras/command-line-interface/commit/3c8faccecfdc72da9127086ee2c6c5ece7da3e25#diff-8a67fad31a23663cae006121d6b49bfd3f448bb12e8b513a78ad2714aa60a7acR204

**Comment by forax** [comment]
I've simplified the design to
- either use a key specified by a user for each argument (enum, string, etc) or use the option first name
- use an `ArgumentBag` as result. `ArgumentBag` abstracts a Map but provides heterogeneous way to extract the value of the arguments (access through flag(),requires(), etc) instead of homogeneous access like an ADT of values.

see https://github.com/sormuras/command-line-interface/blob/353a1fd17428c5e4f8c8505991c48994840bcbf6/test/test/EnumTests.java#L158

Maybe `ArgumentBag` should be augmented with other methods that makes the common operations like asking if an argument is set or not easier ?

**Comment by sormuras** [comment]
I like where this experiment is heading to.

**Comment by jbee** [comment]
For access I'd use `String` of names because 
* no mental mapping from option name to some access object
* no need for extra classes or storing access objects in some constant or variable

For working with the option of the right type I feel all dynamic solutions so far (not including the record one) aren't very handy. With command line options the caller already knows what type the value should (or has to) be. Any code that first needs to inspect or use some sort of dynamic dispatch to get back to the actual type based on what was returned by the slitter will feel unnecessary complex. I feel we should try to think of new solutions that more works like records in that the type of the result is fixed by definition in a way that later also allows accessing it as such value. In contrast to records this solution should allow dynamic composition of options. For example in the scenario that plugin would be allowed to add new options to an application a record cannot be used as it is fix.

**Comment by jbee** [comment]
Forgot: Usuing tests for experiments is a very good idea. We should keep doing that.

**Comment by forax** [comment]
>  I feel we should try to think of new solutions that more works like records in that the type of the result is fixed by definition in a way that later also allows accessing it as such value. 

What about https://github.com/sormuras/command-line-interface/blob/9a75029b7d7633a62fdb8889ef84688860d3123a/test/test/EnumTests.java#L270

**Comment by forax** [comment]
In term of design, we need `Parameter` to be different from `Option` because Java does not support parametrized/generic enums. The result of Splitter.split() has to be an opaque type, here named`DataMap`, instead of a Map<Parameter<?>, Object> because we need to be sure that the objects only comes from calling `split()` not from anywhere else so we already know their types.

**Comment by jbee** [comment]
Yes, that is what I meant (didn't look at the latest update before). That looks good to me. Lets focus on making that smooth(er). BTW I started looking into basic type conversion. I try keep the changes to a minimum but `Option` will get a generic for the type which has to be cascaded to many places.

**Comment by forax** [comment]
> but Option will get a generic for the type which has to be cascaded to many places.
I would prefer the type to be a separated layer on top of Option, exactly like Parameter encapsulate an Option, a "typed Option" does not have to be of type Option

**Comment by jbee** [comment]
> In term of design, we need Parameter to be different from Option

That is a good thing to me. We also want this to be different because it still should be just one way of using options. Records is still a very nice way we want to support. So this really should be two classes with Parameter layering on top of Option.

**Comment by jbee** [comment]
> I would prefer the typing thing to be a separated layer on top of Option, exactly like Parameter encapsulate an Option, a "typed Option" does not have to be of type Option

We can certainly try that. I don't quite see yet how this would look so let me build it function wise and then you can have a go on changing it towards the extra layer.

**Comment by forax** [comment]
Close see 6e396150f1b090d572e04d4c62f9fe73e711935b
