### ISSUE TITLE
A splitter that uses a BRANCH does not fill the required options

### ISSUE THREAD

**Issue by forax** [sormuras/command-line-interface#14]
In https://github.com/sormuras/command-line-interface/blob/main/test/test/BranchTests.java#L24
source and target are required options but not initialized.

**Comment by jbee** [comment]
That is intentional. Often a CLI has a main function and some alternative commands. For example `--help` tends to be such alternative. If these are used the main CLI structure is left for good because the usage has nothing to do with the main function. In the example of help the main command source/target are not needed thus they are set.

**Comment by forax** [comment]
Ah, ok.
Is it an issue if the required option are initialized with null instead of "", now that we support different types ?

**Comment by jbee** [comment]
> Is it an issue if the required option are initialized with null instead of "", now that we support different types ?

Trying to convert `""` to the target type might indeed be an issue we could work around by using `null`. Or we just use `null` as default if the target value type is not `String`.

What we have not defined yet with `BRANCH` options is the role of their position in the sequence of options. 
Currently you can put them anywhere and use them in combination with the options on the level the options branches away from but that is maybe too loose. For example it could be considered an error in usage when an option like a flag is used/set that is defined after the branch option entered.

**Comment by jbee** [comment]
Thinking a bit more about the default value it feels like users should also have ability to set it. This is both a nice feature and a solution to also support primitives where using `null` will not work.

**Comment by forax** [comment]
> Trying to convert "" to the target type might indeed be an issue we could work around by using null. Or we just use null as default if the target value type is not String.

The Option API (unlike the record API) has no notion of value type.

> Thinking a bit more about the default value it feels like users should also have ability to set it. This is both a nice feature and a solution to also support primitives where using null will not work.

you can already almost do it with
```
  Option.ofRequired(...).map(__ -> 0)
```
apart from the fact that i've just disable the function toValue() to be called on required option default value :(

**Comment by forax** [comment]
Closed as this is the intended behavior
