### ISSUE TITLE
Only try factory methods with String and varargs of String

### ISSUE THREAD

**Issue by jbee** [sormuras/command-line-interface#15]
https://github.com/sormuras/command-line-interface/blob/main/main/main/RecordSchemaSupport.java#L114 this is meant to only pick up signatures like `of(String first, String... more)` but currently it will also pick up `of(String first, String[] more)`.

**Comment by jbee** [comment]
@forax Not sure if it is possible but if I am sure you know how.

**Comment by forax** [comment]
You can filter out the MethodHandle with `isVarargsCollector()`

**Comment by forax** [comment]
fixed by 2070ff32ada37d6745535751acf4e0b218037c36
