### ISSUE TITLE
Keep schema for manual

### ISSUE THREAD

**Issue by sormuras** [sormuras/command-line-interface#20]
Using the `record`-based factory to obtain a `Splitter` instance, the option schema is volatile. In order to generate the help message string, it needs to be re-created:

https://github.com/sormuras/bach/blob/891dba3d05882e02d5f26346f5342f8b89f2aada/src/run.bach/main/java/run/bach/Options.java#L48-L53

Should a `Splitter` instance store and provide access to the `Schema` object that was used to configure it?

**Comment by forax** [comment]
This requires to change the Splitter to be a class not a functional interface and makes the preprocessors internal decorators (instead of being an external decorators).
I can do it if you want.

BTW, the linked code should not work anymore given that `RecordSchemaSupport` is not visible anymore
(see https://github.com/sormuras/command-line-interface/commit/f571622f440bdcfd2a6efa3fbd90242c718dc520)

**Comment by forax** [comment]
see https://github.com/sormuras/command-line-interface/pull/21

**Comment by sormuras** [comment]
Happy new year - and yes, a class should do the trick. Or one could also drop the "functional" part of the interface and require implementations to return an instance of the (dynamically or provided) `Schema`.

The linked coded uses "an all is visible distribution" of the classes in the `main` module/package. This "distribution" is generated on-the-fly by: [build/generate.java](https://github.com/sormuras/command-line-interface/blob/main/build/generate.java) and stored in `generated/CommandLineInterface.java`.

**Comment by sormuras** [comment]
Ah, you already saw and improved the generator via https://github.com/sormuras/command-line-interface/commit/f571622f440bdcfd2a6efa3fbd90242c718dc520 and also touch it in #21 ... 👍

**Comment by forax** [comment]
Happy new year too !

**Comment by sormuras** [comment]
Upgraded the single-file source-code "distribution" usage via https://github.com/sormuras/bach/commit/5797f0ca6f241acec72e8bf716ad13351d5fe06a

I'll add the private constructor throwing an assertion error here as well.
