### ISSUE TITLE
Add a way to reflect on converter lambdas

### ISSUE THREAD

**Issue by forax** [sormuras/command-line-interface#22]
Hi all,
i'am exploring a way to load a record and automatically generates the code that will creates the corresponding options,
so it will be easier for user to first specify a record and then transition/refactor the code to use the programmatic API.

One big advantage of the programmatic API is that is does not rely on the reflection/java.lang.invoke API so it works with GraalVM with no modification.

So the idea is to let a user define a record, by example
```java
  record ArgParameters(
        @CommandLineInterface.Help("this is an output")
        Optional<Path> output,
        String className
  ) {}
```
and automatically generates the equivalent code that uses the Option API
```java
import CommandLineInterface.Option;

class Main {
  public static void main(String[] args) {
    var output = Option.single("output").help("this is an output").convert(Path::of);
    var className = Option.required("className");
    var splitter = Splitter.of(output, className);
  }
}
```

for that i need a way to convert a Converter specified as a lambda to the corresponding method reference mirroring the lambda creation.

**Comment by forax** [comment]
fixed by https://github.com/sormuras/command-line-interface/commit/9bde526a9a699fe1f5901373ff20315ba82113aa

**Comment by sormuras** [comment]
Where is the link from `record ArgParameters` to code pasted below? Will take a look a the commit(s). ;-)

**Comment by forax** [comment]
The first parameter of the command optionizer should be the record name.
I use  do a Class.forName() to get the corresponding class which may not be the right way to load it, an URLClassLoader is perhaps a better choice.

**Comment by forax** [comment]
I re-open this given it needs more work
- adding a way to load any record
- recognize any annotations named @Name and @Help so the record at runtime is not dependent of a specific implementation of CommandLineIntereface

**Comment by forax** [comment]
nested schemas are now supported, see https://github.com/sormuras/command-line-interface/commit/4b1762efffc6d2ec73df14db28c627360e46da7b
