### ISSUE TITLE
MethodHandles.publicLookup() is the wrong default

### ISSUE THREAD

**Issue by forax** [sormuras/command-line-interface#6]
There is a variant of ArgumentsSplitter.of() that does not take a Lookup but uses Lookup.publicLookup instead.

I believe using publicLookup is a poor default choice. publicLookup is a very artificial Lookup, it does not exist in real life, it only works for public method of public class of exported package, which means that it will only works if the record is a public record inside an exported package. It's the wrong default because most of the time, you do not want the record to be public, it's either confined to a methd, a class or a package.

I think the variant of ArgumentsSplitter.of() that only takes a Class should be removed, because for beginners trying to use the ArgumentsSplitter the first time, the current behavior is not what beginners will want by default.

**Comment by sormuras** [comment]
Let's remove it - and with it also the `published` tests.

**Comment by forax** [comment]
We can keep the published test and send a public Lookup explicitly if you want
