### ISSUE TITLE
Option model as public API

### ISSUE THREAD

**Issue by jbee** [sormuras/command-line-interface#7]
Currently the splitting could be understood as performing 3 steps

1. deriving an options model from a record class
2. splitting arguments into a canonical list of values for the options model
3. mapping the list of canonical values back into record values

The idea is to make the 2nd step directly accessible so that 1st and 3rd can be optional steps that are wrapped around the 2nd. 
This is so one can use different pre- and post steps. For example creating the options model programmatically.

The canonical value list can be processed differently:
* mapped to a record
* used directly (need to handle/cast from `Object` as different types are used)
* use a ADT pattern with sealed interfaces to put the actual canonical values in a box that can be unpacked using pattern matching 
* convert all canonical values to `String` so a `List<String>` is the result
  * `Optional<String>` => `String` (`""` or the string)
  * `List<String>` => `String` (join with `,` )
  * booleans => `"true"` / `"false"`

### Plan
* make `Option` a top level type and part of the public API
* extract `ArgumentsProcessor` to a true pre-processing step
* make the splitter only operate on the options model
* add entry methods that do the original 3 steps for records
* add entry methods that give access to only the splitting

**Comment by jbee** [comment]
See https://github.com/sormuras/command-line-interface/pull/8

**Comment by forax** [comment]
Counter proposal, same idea, slightly different refactoring
https://github.com/sormuras/command-line-interface/pull/9

The ArgumentSplitter API is the same, but now you can create a schema without using a record.

**Comment by sormuras** [comment]
Went with #8 including ideas from #9 - let's see where we go from here.

**Comment by forax** [comment]
Yes, i will fix the different issues in different commits,
- using `Collection` is used by the algo requires an order so `List` should be used instead (Collection has no defined order),
- some methods are not public, some methods should not be public,
- there are some missing wildcards
- there are some missing requireNonNull / preconditions to avoid modification after creation.
- I believe we can use the Value hierarchy directly in split() avoiding to upcast everything to Object (maybe we can remove all these pesky SuppressWarnings)

but i have no idea why there is the notion of pruned and always when evaluating values

**Comment by jbee** [comment]
Sounds good. 

The pruned was just an idea that sometimes a caller might want only values that are not empty/default and sometimes all possible options should be converted to their values because matching them to options would be index based. 

But this entire `List<Value>` is unwieldy. Christian started to use it in a test and soon found a `Map<Option,Value>` or `Map<String,Value>` might be much better. With a map it might make sense to always just include options that did occur in the input. Getting rid of this pesky prune flag. 

The entire `Value` ADT is really just a big experiment at this point to see if an ADT can be used to make working with options somewhat smooth. As it is now it is not very handy but maybe you have some ideas?
